import Image from "next/image";
import React from "react";
import QRCODE from "@/assets/icon/qr_code.png";

export default function page() {
    return (
        <section className="bg-white font-[500] text-[#353535]">
            <div>
                <p className="p-4 text-[24px] capitalize">
                    Connect with your authenticator apps
                </p>
                <hr />
                <div className="flex flex-row justify-between p-4">
                    <div>
                        <h1 className="text-[32px] capitalize">
                            {" "}
                            Multi-Factor Authentication
                        </h1>
                        <div className="font-[400] ">
                            <ol className="list-decimal gap-2 pl-6">
                                <li>
                                    You will need an authenticator mobile app to
                                    complete this process, such as one of the
                                    following:
                                    <ul className="list-disc pl-6 text-[#0C8CE9]">
                                        <li>Google Authenticator</li>
                                        <li>Authy</li>
                                    </ul>
                                </li>
                                <li>
                                    Scan the QR code with your authenticator
                                </li>
                                <p className="text-[#6B7280]">
                                    {" "}
                                    If you can’t scan the code, you can enter
                                    this secret key into your authentication app
                                </p>
                                <li>
                                    After scanning the QR code above, enter the
                                    six-digit code generated by your
                                    authenticator
                                </li>
                            </ol>
                        </div>
                    </div>
                    <div>
                        <Image
                            src={QRCODE}
                            height={1080}
                            width={1920}
                            alt="QR Code"
                            className="h-[300px] w-[300px]"
                        />
                    </div>
                </div>
            </div>
        </section>
    );
}
